import { createClient } from "https://esm.sh/@supabase/supabase-js@2";

const supabaseUrl = Deno.env.get("SUPABASE_URL")!;
const supabaseServiceKey = Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!;

const supabase = createClient(supabaseUrl, supabaseServiceKey);

Deno.serve(async (req) => {
  // 1. Only allow POST requests
  if (req.method !== "POST") {
    return new Response(JSON.stringify({ error: "Method not allowed" }), {
      status: 405,
    });
  }

  const {
    appointmentId,
    labId,
    amount,
    paymentMethod,
    transactionRef,
    notes, // Added to match your new schema
  } = await req.json();

  // 2. Validate required fields (matching your 'is_nullable: NO' constraints)
  if (!appointmentId || !labId || !amount || !paymentMethod) {
    return new Response(
      JSON.stringify({ error: "Missing required fields" }),
      { status: 400 }
    );
  }

  // 3. Verify appointment exists and belongs to this lab
  const { data: appt, error: aptError } = await supabase
    .from("appointments")
    .select("id, lab_id, booking_id") 
    .eq("id", appointmentId)
    .eq("lab_id", labId)
    .single();

  if (aptError || !appt) {
    return new Response(
      JSON.stringify({ error: "Appointment not found" }),
      { status: 404 }
    );
  }

  // 4. Payment Gateway Placeholder (Razorpay, Cashfree, etc.)
  if (paymentMethod === "gateway_automated") {
    // const gatewayVerified = await verifyPaymentSignature(req);
    // if (!gatewayVerified) throw new Error("Invalid signature");
  }

  // 5. Insert payment record matching your exact schema
  const { data: payment, error: paymentError } = await supabase
    .from("payments")
    .insert([
      {
        appointment_id: appointmentId,
        lab_id: labId,
        amount_paid: amount,
        payment_method: paymentMethod,
        transaction_ref: transactionRef || null,
        payment_status: "paid", // Matches your default
        notes: notes || null,   // Maps to your optional notes column
        // 'id' and 'created_at' are automatically generated by Postgres defaults!
      },
    ])
    .select()
    .single();

  if (paymentError) {
    return new Response(
      JSON.stringify({ error: paymentError.message }),
      { status: 400 }
    );
  }

  // 6. Return success
  return new Response(JSON.stringify(payment), {
    headers: { "Content-Type": "application/json" },
  });
});